FROM node:18-alpine as builder

WORKDIR /frontend

COPY ./frontend/package.json ./frontend/package-lock.json ./

RUN npm i

COPY ./frontend .

RUN npm run build --prod

FROM nginx:alpine

COPY ./config/dev/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /frontend/dist/frontend /usr/share/nginx/html/

VOLUME ["/etc/nginx/ssl"]

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
