name: Release CI/CD Pipeline
run-name: ${{ github.actor }} triggered release
on:
  push:
    branches:
      - 'releases/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: maven
          path: backend
      - name: Package the artefact
        run: mvn -B package -DskipTests --file pom.xml
      - name: Run Unit tests
        run: mvn surefire:test
      - name: Run Integration tests
        run: mvn failsafe:integration-test failsafe:verify
      - name: Deploy
        run: echo "Deployed"

      
